name: VPS Tailscale
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connexion Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

      - name: Lancer SSH sur le port 2222
        run: |
          # 1. Définir le mot de passe 'root' pour runner
          echo "runner:root" | sudo chpasswd
          
          # 2. Générer les clés d'hôte SSH si absentes
          sudo ssh-keygen -A
          
          # 3. Lancer une instance SSH dédiée
          sudo /usr/sbin/sshd -p 2222 -o "PasswordAuthentication=yes" -o "PermitRootLogin=yes"
          
          echo "Serveur SSH actif sur le port 2222 !"

      - name: Maintenir la session
        run: sleep 21600
